FROM codercom/code-server:latest

RUN code-server --install-extension reditorsupport.r
RUN code-server --install-extension rdebugger.r-debugger
RUN code-server --install-extension rconsole.vsc-r-console
